# content of pytest.ini
# Example 1: have pytest look for "check" instead of "test"
[pytest]
addopts = -s -v
python_files = check_*.py
python_classes = Check
python_functions = check_*
markers =
    testslow: marks test as slow, (deselect with '-m \"not slow\"')
    ibatconnected: tests which need an active ibat connection, (deselect with '-m \"not ibatconnected\"')
